---

- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Run day1 role for task1
      ansible.builtin.include_role:
        name: day1
        tasks_from: task1.yml
      vars:
        day1_input1: "{{ lookup('file', 'day1_test_input1.txt') }}"
    - name: Read output
      ansible.builtin.set_fact:
        day1_output: "{{ lookup('file', 'out/day1_result1.txt') | trim }}"
    - name: Assert correct value
      ansible.builtin.assert:
        that:
          - day1_output | int == 11

    - name: Run day1 role for task2
      ansible.builtin.include_role:
        name: day1
        tasks_from: task2.yml
      vars:
        day1_input2: "{{ lookup('file', 'day1_test_input1.txt') }}"
    - name: Read output
      ansible.builtin.set_fact:
        day1_output: "{{ lookup('file', 'out/day1_result2.txt') | trim }}"
    - name: Assert correct value
      ansible.builtin.assert:
        that:
          - day1_output | int == 31

    - name: Run day2 role for task1
      ansible.builtin.include_role:
        name: day2
        tasks_from: task1.yml
      vars:
        day2_input1: "{{ lookup('file', 'day2_test_input1.txt') }}"
    - name: Read output
      ansible.builtin.set_fact:
        day2_output: "{{ lookup('file', 'out/day2_result1.txt') | trim }}"
    - name: Assert correct value
      ansible.builtin.assert:
        that:
          - day2_output | int == 2

    - name: Run day2 role for task2
      ansible.builtin.include_role:
        name: day2
        tasks_from: task2.yml
    - name: Read output
      ansible.builtin.set_fact:
        day2_output: "{{ lookup('file', 'out/day2_result2.txt') | trim }}"
    - name: Assert correct value
      ansible.builtin.assert:
        that:
          - day2_output | int == 4

    - name: Run day6 role for task1
      ansible.builtin.include_role:
        name: day6
        tasks_from: task1.yml
    - name: Read output
      ansible.builtin.set_fact:
        day6_output: "{{ lookup('file', 'out/day6_result1.txt') | trim }}"
    - name: Assert correct value
      ansible.builtin.assert:
        that:
          - day6_output | int == 41
