---

- name: Assert input is correct
  ansible.builtin.assert:
    that:
      - day1_input1
      - day1_input1 is string
      - day1_input1 | length > 0

- name: Read input into list
  ansible.builtin.set_fact:
    input_lines: "{{ day1_input1.split('\n') }}"

- name: Get and sort list1
  ansible.builtin.set_fact:
    list1: "{{ input_lines | map('split', ' ') | map('first') | map('int') | list | sort }}"

- name: Get and sort list2
  ansible.builtin.set_fact:
    list2: "{{ input_lines | map('split', ' ') | map('last') | map('int') | list | sort }}"

- name: Set combined list fact by zipping and sorting low to high
  ansible.builtin.set_fact:
    combined_list: "{{ list1 | zip(list2) | map('sort') }}"

- name: Calculate sum of distances
  ansible.builtin.set_fact:
    sum_of_distances: "{{ sum_of_distances | default(0) | int + (item.1 - item.0) }}"
  with_list: "{{ combined_list }}"

- name: Write result
  delegate_to: localhost
  block:
    - name: Ensure output directory exists  # noqa: risky-file-permissions
      ansible.builtin.file:
        path: "{{ playbook_dir }}/out"
        state: directory

    - name: Write result to file  # noqa: risky-file-permissions
      ansible.builtin.copy:
        content: "{{ sum_of_distances }}"
        dest: "{{ playbook_dir }}/out/day1_result1.txt"
