---

- name: Handle subsequent numbers to first
  when: not ansible_loop.first and report_is_safe
  block:
    - name: Set report_is_safe to false if current_number equals previous_number
      ansible.builtin.set_fact:
        report_is_safe: false
      when: current_number == ansible_loop.previtem

    - name: Determine if report is increasing
      ansible.builtin.set_fact:
        report_is_increasing: "{{ current_number | int > (ansible_loop.previtem | int) }}"
      when: ansible_loop.index0 == 1

    - name: Set report_is_safe to false if current_number is not greater than previous_number or difference is greater than 3
      ansible.builtin.set_fact:
        report_is_safe: false
      changed_when: true
      when: report_is_increasing and
        (not current_number | int > (ansible_loop.previtem | int) or
        current_number | int - (ansible_loop.previtem | int) > 3)

    - name: Set report_is_safe to false if current_number is not less than previous_number or difference is greater than 3
      ansible.builtin.set_fact:
        report_is_safe: false
      changed_when: true
      when: not report_is_increasing and
        (not current_number | int < (ansible_loop.previtem | int) or
        (ansible_loop.previtem | int) - current_number | int > 3)

- name: Increment safe_reports if report is safe and this is the last loop iteration
  ansible.builtin.set_fact:
    safe_reports: "{{ safe_reports | int + 1 }}"
  when: report_is_safe and ansible_loop.last
