on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      # Set ANSIBLE_ROLES_PATH to the directory where the roles are located
      - name: Set ANSIBLE_ROLES_PATH
        run: echo "ANSIBLE_ROLES_PATH=/${{ github.repository }}/ifalatik/aoc2024/roles" >> $GITHUB_ENV
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}/ifalatik/aoc2024/extensions"
