on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      # Copy roles
      - name: Copy roles to directory used by molecule
        run: cp -r ${{ github.repository }}/ifalatik/aoc2024/roles/ ${{ github.repository }}/ifalatik/aoc2024/extensions/molecule/default/
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}/ifalatik/aoc2024/extensions"
