on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "~/.ansible/collections/ansible_collections/ifalatik/aoc2024/${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "~/.ansible/collections/ansible_collections/ifalatik/aoc2024/${{ github.repository }}/extensions"
