on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "ifalatik/aoc2024/${{ github.repository }}"
      # move molecule directory to the root of the repository
      - run: mv "ifalatik/aoc2024/${{ github.repository }}/extensions/molecule" "ifalatik/aoc2024/${{ github.repository }}/molecule"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "ifalatik/aoc2024/${{ github.repository }}"
