on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "collections/ansible_collections/ifalatik/aoc2024"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r collections/ansible_collections/ifalatik/aoc2024/.devcontainer/requirements.txt
      - name: Move molecule directory
        run: mv "${{ github.workspace }}/collections/ansible_collections/ifalatik/aoc2024/extensions/molecule" "${{ github.workspace }}/collections/ansible_collections/ifalatik/aoc2024/molecule"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.workspace }}/collections/ansible_collections/ifalatik/aoc2024"
        env:
          ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/../../../:~/.ansible/collections:/usr/share/ansible/collections
          ANSIBLE_ROLES_PATH: ${{ github.workspace }}/roles:~/.ansible/roles:/usr/share/ansible/roles
