on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "collections/ansible_collections/ifalatik/aoc2024"
      # move molecule directory to the root of the repository
      - run: mv "${{ github.workspace }}/collections/ansible_collections/ifalatik/aoc2024/extensions/molecule" "${{ github.workspace }}/collections/ansible_collections/ifalatik/aoc2024/molecule"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.workspace }}/collections/ansible_collections/ifalatik/aoc2024"
        env:
          ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/../../../:~/.ansible/collections:/usr/share/ansible/collections
          ANSIBLE_ROLES_PATH: ${{ github.workspace }}/roles:~/.ansible/roles:/usr/share/ansible/roles
